source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MMTransitionAnimator_Example', :exclusive => true do
  pod 'MMTransitionAnimator', :path => '../'
end

target 'MMTransitionAnimator_Tests', :exclusive => true do
  pod 'MMTransitionAnimator', :path => '../'

  
end
